### ISSUE TITLE
Command line to compile binary

### ISSUE THREAD

**Issue by Serizao** [Dfte/Impersonate#1]
Hello, nice binary, can you specifyg a commande line to compile it. I try with gcc and VS2019 but in both case i have some errors

**Comment by Dfte** [comment]
Hello Serizao, first of all sorry for not answering before... I have been working on a new version of this binary as well as a blog post which is going to be released on monday. The new repository will contain all the compilation information as well as the new version of the binary. I'll send you the link to the repo later :)

**Comment by Dfte** [comment]
Here you go :) https://github.com/sensepost/impersonate
